### ISSUE TITLE
Error en Eclipse por archivos proto generados

### ISSUE THREAD

**Issue by marcalwestf** [solop-develop/adempiere-grpc-server#219]
Luego de generar con `gradle build` los archivos gRPC, y refrescar el proyecto, aparecen errores en los archivos generados de tipo _proto_:
![image](https://user-images.githubusercontent.com/1789408/220784006-7ae9112e-a55a-43dc-9ce2-73eea583a19f.png)

Pasos para reproducir:
- Ubuntu 18.02
- JDK y nivel de compilación: 17
![image](https://user-images.githubusercontent.com/1789408/220785115-b9bf9b40-8bd5-4a4d-abfb-9cbaf9616eaa.png)
![image](https://user-images.githubusercontent.com/1789408/220785153-b3103ef0-0d4a-4fb9-a812-75bc68187253.png)
- gradle clean (en Eclipse o en consola)
- gradle build (en Eclipse o en consola)
- Refresh Gradle Project

No encuentro en ningún lugar cómo evitar por ejemplo la creación de `option go_package`.

**Comment by EdwinBetanc0urt** [comment]
Hola @marcalwestf aun persiste el error?
