### ISSUE TITLE
Warehouse no cargado en Contexto

### ISSUE THREAD

**Issue by rcapecce** [solop-develop/adempiere-grpc-server#512]
Se detecta que en SecurityServiceImplementation.java que no se está definiendo el warehouse al momento de cargarlo en la organización.
Se debe corregir para obtener uno por defecto.
Adicionalmente se debe revisar cuando se realiza el cambio de rol y org que permita tomar el almacen seleccionado.

https://github.com/solop-develop/adempiere-grpc-server/blob/f626c5764ce0b16af44743ea1cceb674f6849d10/src/main/java/org/spin/grpc/service/SecurityServiceImplementation.java#L594

**Comment by EdwinBetanc0urt** [comment]
Esto fue corregido
