### ISSUE TITLE
error: Consulta Inteligente Referencia Tabla incorrecta

### ISSUE THREAD

**Issue by rcapecce** [solop-develop/adempiere-grpc-server#514]
Se detecta que en un SB al utilizar una referencia Tabla en un campo del mismo, el mismo crea una sql con campos a otra tabla, como ahí no existen entonces da error no encontrando registros.

Replicable en http://host.solopapp.com:24145/

Proyecto 1559, SB "Crear Checking"

El campo C_ProjectCategory_ID está generando una SQL aparentemente para la referencia Tabla que joinea contra la C_Order siendo que ahí no existe ese campo.

*Definición del Campo*

![image](https://github.com/solop-develop/adempiere-grpc-server/assets/14218144/2eab5881-0052-4047-94ba-0062497633ea)

Se observa que el siguiente error en el backend al abrir el SB y no genera la búsqueda.
`Caused by: org.postgresql.util.PSQLException: ERROR: no existe la columna so.c_projectcategory_id`
Si el campo se desactiva entonces no falla.

**Comment by EdwinBetanc0urt** [comment]
![imagen](https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/ac4828de-72fb-4b20-8d68-ac9c1cbde3dc)
