### ISSUE TITLE
Error al crear Recepción desde Express Receipt

### ISSUE THREAD

**Issue by rcapecce** [solop-develop/adempiere-grpc-server#581]
Se detecta que no se puede guardar al MInOut debido a que no se le establece MovementType

El asunto comienza acá, al momento de crear la recepción, le pasan el docTypeShipmentId en 0

https://github.com/solop-develop/adempiere-grpc-server/blob/79c6ac12711445840baaec197dd49b4ebf7d9578/src/main/java/org/spin/grpc/service/ExpressReceiptServiceImplementation.java#L504

Por ser 0 no puede establecer el MovementType y al guardar da SaveError

https://github.com/solop-develop/adempiere-box/blob/5fc84c4f87de754c6b2cc715e4d5c779c387ad5f/base/src/org/compiere/model/MInOut.java#L376

Como debería solucionarse esto @EdwinBetanc0urt ? deberían seleccionar alguno predefinido?, o establecer hardcode antes de guardar el MovementType?

**Comment by EdwinBetanc0urt** [comment]
El tipo de documento de la orden debe tener configurado el tipo de documento para entregas, así al crearlo desde la orden establecerá correctamente el tipo de movimiento


![imagen](https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/6fb58a68-ecac-4256-8848-337be23e6888)

![imagen](https://github.com/solop-develop/adempiere-grpc-server/assets/20288327/71f994fb-25dd-4fb7-ab23-822aedaf9e34)

**Comment by EdwinBetanc0urt** [comment]
De igual manera se agrego que de forma predeterminada agregue el tipo de movimiento, y un `warning` al log si el tipo de documento de la orden no tiene configurado tipo de documento de entrega.
