### ISSUE TITLE
Endpoint duplicado listar socios de negocio y listar clientes

### ISSUE THREAD

**Issue by Ricargame** [solop-develop/adempiere-grpc-server#700]
https://github.com/solop-develop/adempiere-grpc-server/blob/develop/src/main/proto/core_functionality.proto#L133

Servicio duplicado con crear cliente de punto de venda 

```proto
CreateBusinessPartner(CreateBusinessPartnerRequest) returns (BusinessPartner) {
		option (google.api.http) = {
			post: "/core-functionality/business-partners",
			body: "*"
		};
	}
```

https://github.com/solop-develop/adempiere-grpc-server/blob/develop/src/main/proto/point_of_sales.proto#L197
```proto
CreateCustomer(CreateCustomerRequest) returns (Customer) {
		option (google.api.http) = {
			post: "/point-of-sales/customers",
			body: "*"
		};
	}
```

**Comment by EdwinBetanc0urt** [comment]
Esta validación es mas a nivel técnico no cambia nada a nivel funcional
